package security

// Create cacheable values that expire
// some requests can be restricted for a code, 2FA or some validation token
// those requests can be identified with a key, generated by userid/clientidentificator/cookie/ip
// later those keys are challenged and set to true in the backend, then those request validations
// will allow the requests to pass

// Use cases:
// 1 - Preventing bots from requesting an endpoint.
//   -  Create a Proof before registering and requiring
// 2 - Require user input for a specific action, like changing username or changing a system defined value
//
